version: '3.6'  
services:  
  nestor_slack_reader:
    build:
      context: ./nestor_slack_reader
    container_name: nestor_slack_reader
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
    networks:
      - network

  nestor_persistence:
    build:
      context: ./nestor_persistence
    container_name: nestor_persistence
    networks:
      - network
    environment:
      - MONGO_HOST=database
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - database
      - rabbitmq

  database:
    image: mongo
    container_name: nestor_mongo
    networks:
      - network
    environment:
      - MONGO_INITDB_DATABASE=nestor
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
    container_name: rabbitmq
    restart: 'always'

networks:
  network: {}





